/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --strict-vars=false --env-interface=CloudflareEnv cloudflare-env.d.ts` (hash: b660eb1c3f2623119807259eca537cce)
interface __BaseEnv_CloudflareEnv {
	KV: KVNamespace;
	ASSETS: Fetcher;
	RESEARCH_MODEL: string;
	WRITER_MODEL: string;
	IMAGE_PROVIDER: string;
	IMAGE_SIZE: string;
	PUBLIC_BASE_URL: string;
	LINKEDIN_REDIRECT_URI: string;
	ANTHROPIC_API_KEY: string;
	RESEND_API_KEY: string;
	EMAIL_FROM: string;
	EMAIL_TO: string;
	LINKEDIN_CLIENT_ID: string;
	LINKEDIN_CLIENT_SECRET: string;
	LINKEDIN_ACCESS_TOKEN: string;
	LINKEDIN_AUTHOR_URN: string;
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_CloudflareEnv {}
}
interface CloudflareEnv extends __BaseEnv_CloudflareEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "RESEARCH_MODEL" | "WRITER_MODEL" | "IMAGE_PROVIDER" | "IMAGE_SIZE" | "PUBLIC_BASE_URL" | "LINKEDIN_REDIRECT_URI" | "ANTHROPIC_API_KEY" | "RESEND_API_KEY" | "EMAIL_FROM" | "EMAIL_TO" | "LINKEDIN_CLIENT_ID" | "LINKEDIN_CLIENT_SECRET" | "LINKEDIN_ACCESS_TOKEN" | "LINKEDIN_AUTHOR_URN">> {}
}
