// Minimal Cloudflare runtime types for the bindings this app actually uses.
//
// We deliberately do NOT pull in `@cloudflare/workers-types` (or the full
// `wrangler types` runtime output): those redeclare DOM globals like `Request`,
// `Response` and `fetch`, which collide with `lib: ["DOM"]` that Next.js and
// React need. `cloudflare-env.d.ts` (generated by `npm run cf-typegen`) only
// references the two names below, so this shim is all that is missing.

declare global {
  /** Workers KV — the subset used by jobStore / connectionStore / oauthState. */
  interface KVNamespace {
    get(key: string): Promise<string | null>;
    get(key: string, type: "text"): Promise<string | null>;
    get<T>(key: string, type: "json"): Promise<T | null>;
    get(key: string, type: "arrayBuffer"): Promise<ArrayBuffer | null>;

    put(
      key: string,
      value: string | ArrayBuffer | ArrayBufferView,
      options?: { expiration?: number; expirationTtl?: number; metadata?: unknown },
    ): Promise<void>;

    delete(key: string): Promise<void>;
  }

  /** A bound Worker/service (here: the static-asset binding OpenNext adds). */
  interface Fetcher {
    fetch(input: RequestInfo | URL, init?: RequestInit): Promise<Response>;
  }
}

export {};
